#VARIABLES= definition2
F90 = gfortran
TARGET=ff
OBJECTS = $(TARGET).o
FCFLAGS = -Ofast -g -pg -fbounds-check

#all: clean run

#compile
$(TARGET): $(OBJECTS)
	$(F90) $(FCFLAGS) -o $(TARGET) $(OBJECTS)

#$(TARGET).o:  $(TARGET).f90
#       $(F90) $(FCFLAGS) -c $(TARGET).f90
%.o: %.f90
	$(F90) $(FCFLAGS) -c $^
run:
	./$(TARGET)
	gprof $(TARGET) gmon.out > ff_analysis.txt

.PHONY:clean

clean:
	rm -rf $(TARGET) $(OBJECTS) *.out *.o
